version: "3"
services:

  gateway:
    image: nginx:latest
    depends_on:
        - rabbitmq
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-service:
    build: ./order
    image: order:latest
    container_name: order-service
    restart: always
    depends_on:
        - rabbitmq
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/order_mongo.env

  stock-service:
    build: ./stock
    image: stock:latest
    container_name: stock-service
    restart: always
    depends_on:
        - rabbitmq
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/stock_mongo.env

  payment-service:
    build: ./payment
    image: user:latest
    container_name: payment-service
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/payment_mongo.env

  order-db:
    build: ./mongo/
    container_name: order-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    command: ["--bind_ip_all", "--replSet", "order", "--keyFile", "/keyfiles/order-keyfile"]

  stock-db:
    build: ./mongo/
    container_name: stock-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    command: ["--bind_ip_all", "--replSet", "stock", "--keyFile", "/keyfiles/stock-keyfile"]

  payment-db:
    build: ./mongo/
    container_name: payment-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    command: ["--bind_ip_all", "--replSet", "payment", "--keyFile", "/keyfiles/payment-keyfile"]

  mongosetup:
    image: "mongo-setup"
    build: "./mongo-setup"
    container_name: "mongosetup"
    depends_on:
        - order-db
        - stock-db
        - payment-db
    volumes:
        - mongostatus:/data/
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    # environment:
    #   RABBITMQ_DEFAULT_USER: guest
    #   RABBITMQ_DEFAULT_PASS: guest
    #   RABBITMQ_ERLANG_COOKIE: guest
    #   RABBITMQ_DEFAULT_VHOST: /
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    depends_on:
      - mongosetup
    # volumes:
    #   - rabbitmq:/data/

volumes:
  mongostatus: