apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
