apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - image: nginx:latest
          name: gateway
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
