apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: stock-service
  name: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stock-service
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: stock-service
    spec:
      containers:
        - args:
            - gunicorn
            - -b
            - 0.0.0.0:5000
            - app:app
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  key: MONGO_HOST
                  name: env-stock-mongo-env
            - name: MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_PASSWORD
                  name: env-stock-mongo-env
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  key: MONGO_PORT
                  name: env-stock-mongo-env
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_USERNAME
                  name: env-stock-mongo-env
          image: stock:latest
          imagePullPolicy: IfNotPresent
          name: stock-service
          resources: {}
      restartPolicy: Always
status: {}
